# Generated by Django 5.2.4 on 2025-07-04 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_accomplishedby_office_workorderrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='entity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entity'),
        ),
    ]
