# Generated by Django 5.2.4 on 2025-07-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_computer_entity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_lname', models.CharField(max_length=100)),
                ('borrower_fname', models.CharField(max_length=100)),
                ('borrower_mi', models.CharField(max_length=10)),
                ('datetime_borrowed', models.DateTimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('action_taken', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('renewed', 'Renewed'), ('damaged', 'Damaged')], max_length=20)),
                ('remarks', models.CharField(max_length=255)),
                ('datetime_returned', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.accomplishedby')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.entity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.office')),
            ],
        ),
    ]
