# Generated by Django 5.2.4 on 2025-07-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_computer_lab_equipment_computer_operating_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Under Maintenance', 'Under Maintenance'), ('Offline', 'Offline')], default='operational', max_length=20),
        ),
    ]
